title: OSSANG
description: Developer Blog
author: Oh Sang Heon
logo: /ossang.github.io/static/img/avatar.png
github: https://github.com/ossang/ossang.github.io
about: ossangheon@gmail.com  

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
